### ISSUE TITLE
Awesome stuff man, I'm looking forward to what's next

### ISSUE THREAD

**Issue by naltun** [s0md3v/nano#1]
:+1: :+1: :+1:

I've a bit of experience with PHP, but I'm by no means the most experienced PHP hacker. That being said, I'm impressed so far with nano and I'm excited for what's to come. Btw, awesome use of 39 chars :+1: I am quite the fan of PHP's flexibility.

I'm watching the repo eagerly man. Best of luck!

**Comment by s0md3v** [comment]
Thanks for appreciating fam, it really means a lot to me ^_^
